import Head from "next/head";
import { Inter } from "next/font/google";
import Carousel from "@/components/Carousel";
import WhoAmI from "@/components/WhoAmI";
import ProjectBlock from "@/components/ProjectBlock";
import projects from "@/data/projects.json";
import AboutMe from "@/components/AboutMe";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Flunflun Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WhoAmI />
        <ProjectBlock projects={projects} />
        <AboutMe />
      </main>
    </>
  );
}
